import React, { useState } from 'react';
import { FileText, Copy, Check, Download, Eye, Code, BookOpen, Layers } from 'lucide-react';
import { LatexRenderer } from './LatexRenderer';
import { DocumentStructuralMetadata } from '../types';

interface MarkdownLinearizedViewProps {
  markdownContent?: string;
  paperTitle: string;
  documentMetadata?: DocumentStructuralMetadata;
}

export const MarkdownLinearizedView: React.FC<MarkdownLinearizedViewProps> = ({
  markdownContent = '',
  paperTitle,
  documentMetadata,
}) => {
  const [isCopied, setIsCopied] = useState(false);
  const [viewMode, setViewMode] = useState<'rendered' | 'raw'>('rendered');

  const content = markdownContent || `# ${paperTitle}\n\n*Linearized academic Markdown generated by 3-page windowed IDP parser.*`;
  const words = content.split(/\s+/).filter(Boolean).length;

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${paperTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_linearized.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white border border-slate-200/80 rounded-2xl shadow-xs p-6 sm:p-8 space-y-5 text-slate-800">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-slate-200/80">
        <div>
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-indigo-600" strokeWidth={2} />
            <h3 className="text-base font-bold text-slate-900 font-sans tracking-tight">
              Linearized Academic Markdown Document
            </h3>
            <span className="px-2.5 py-0.5 rounded-full text-[11px] font-mono bg-indigo-50 text-indigo-700 border border-indigo-200/80 font-bold">
              3-Page Windowed IDP
            </span>
          </div>
          <p className="text-xs sm:text-sm text-slate-600 mt-1 leading-relaxed">
            Normalized multi-column text, LaTeX formulas, and Markdown pipe tables parsed via sequential rolling context chaining.
          </p>
        </div>

        {/* Action Controls */}
        <div className="flex items-center gap-2 flex-wrap">
          <div className="flex items-center bg-slate-100 p-1.5 rounded-xl border border-slate-200/80 text-xs shadow-2xs">
            <button
              onClick={() => setViewMode('rendered')}
              className={`px-3 py-1.5 rounded-lg font-semibold flex items-center gap-1.5 transition-all ${
                viewMode === 'rendered'
                  ? 'bg-white text-slate-900 font-bold shadow-2xs'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              <Eye className="w-3.5 h-3.5" />
              <span>Formatted</span>
            </button>
            <button
              onClick={() => setViewMode('raw')}
              className={`px-3 py-1.5 rounded-lg font-semibold flex items-center gap-1.5 transition-all ${
                viewMode === 'raw'
                  ? 'bg-white text-slate-900 font-bold shadow-2xs'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              <Code className="w-3.5 h-3.5" />
              <span>Raw (.md)</span>
            </button>
          </div>

          <button
            onClick={handleCopy}
            className="px-3.5 py-2 rounded-xl bg-white hover:bg-slate-50 text-slate-700 text-xs font-semibold border border-slate-300 flex items-center gap-1.5 transition-colors shadow-2xs"
          >
            {isCopied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-500" />}
            <span>{isCopied ? 'Copied!' : 'Copy .md'}</span>
          </button>

          <button
            onClick={handleDownload}
            className="px-3.5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-semibold flex items-center gap-1.5 transition-all shadow-2xs"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download .md</span>
          </button>
        </div>
      </div>

      {/* Structural Metadata Strip */}
      <div className="flex items-center gap-3 text-xs font-mono text-slate-700 bg-slate-50/80 px-4 py-2.5 rounded-xl border border-slate-200/80 flex-wrap">
        {documentMetadata ? (
          <>
            <span className="font-semibold text-indigo-900">
              📄 {documentMetadata.totalPages} Pages
            </span>
            <span>•</span>
            <span className="text-slate-800">📊 {documentMetadata.totalFigures} Figures</span>
            <span>•</span>
            <span className="text-slate-800">📋 {documentMetadata.totalTables} Tables</span>
            <span>•</span>
            <span className="text-slate-800">📚 {documentMetadata.totalReferences} References</span>
            <span>•</span>
            <span className="text-slate-800">📑 {documentMetadata.totalSections} Sections</span>
          </>
        ) : (
          <>
            <span>Word Count: <strong className="text-slate-900">{words.toLocaleString()} words</strong></span>
            <span>•</span>
            <span>Format: <strong className="text-emerald-700 font-semibold">GitHub Flavored Markdown (GFM)</strong></span>
          </>
        )}
      </div>

      {/* Document Preview Box */}
      <div className="p-8 rounded-2xl bg-white border border-slate-200/70 shadow-2xs">
        {viewMode === 'rendered' ? (
          <div className="space-y-4 text-slate-800 leading-relaxed font-sans">
            <LatexRenderer text={content} />
          </div>
        ) : (
          <pre className="font-mono text-xs text-indigo-950 bg-slate-50 p-6 rounded-xl border border-slate-200/80 whitespace-pre-wrap leading-relaxed">
            {content}
          </pre>
        )}
      </div>
    </div>
  );
};
